import {z} from "zod";
import raw from "@/data/projects.json";
import archive from "@/data/profile-archive.json";
const publicIds = new Set(["trace-fangeo", "vorom-x-aerodynamics", "high-lift-aerodynamics", "apexsim-aerodynamics", "dep-aircraft-aero", "lilium-sandwich-structures", "feynman-fixed-wing-uav", "warr-cryotank-fea", "gpr-drone", "rc-aircraft", "satellite-design", "baja-sae"]);
const schema=z.object({id:z.string(),title:z.string(),role:z.string(),tags:z.array(z.string()),tools:z.array(z.string()),impact:z.string(),summary:z.string(),problem:z.string(),approach:z.string(),methods:z.string(),validation:z.string(),results:z.string(),learnings:z.string(),next_steps:z.string()});
export const work=z.array(schema).parse(raw.filter(p=>publicIds.has(p.id)));
export const inventory=archive;
export type Project=z.infer<typeof schema>;
export const locales=["en","fr","de"] as const;
export type Locale=typeof locales[number];
export const messages={
 en:{personal:"Personal",professional:"Professional",work:"Work",profile:"Profile",contact:"Contact",search:"Search",cv:"Download CV",intro:"Aerospace, from another perspective.",human:"Engineering is how I think. Movement is how I see.",bio:"Aerodynamics and propulsion. A mechanical engineering foundation. A life between India, Munich and Toulouse — with a fascination for the way things move.",selected:"Selected work",research:"From a requirement to a model.",explore:"Explore the research",archive:"Explore the full profile",fallback:"Technical records are presented in their original English. Interface language does not indicate spoken proficiency.",overview:"Aerodynamics. Propulsion. Computational methods.",proIntro:"Research at ISAE-SUPAERO, graduate aerospace studies at TUM and mechanical design experience at Lilium. Physical modelling, scientific Python and aerospace test hardware.",evidence:"Evidence, before claims.",all:"All",close:"Close",find:"Find a project, topic or page",none:"No matches. Try another term.",journey:"One trajectory. Three perspectives.",touch:"Let’s discuss the work.",print:"Print profile",capabilities:"Capabilities, connected to work."},
 fr:{personal:"Personnel",professional:"Professionnel",work:"Projets",profile:"Profil",contact:"Contact",search:"Rechercher",cv:"Télécharger le CV",intro:"L’aérospatiale, sous un autre angle.",human:"L’ingénierie façonne ma pensée. Le mouvement, mon regard.",bio:"Aérodynamique et propulsion. Une formation en génie mécanique. Un parcours entre l’Inde, Munich et Toulouse — et une fascination pour le mouvement.",selected:"Projets sélectionnés",research:"Du besoin au modèle.",explore:"Explorer la recherche",archive:"Explorer le profil complet",fallback:"Les dossiers techniques sont présentés dans leur version anglaise originale. La langue de l’interface n’indique pas le niveau linguistique.",overview:"Aérodynamique. Propulsion. Méthodes numériques.",proIntro:"Recherche à l’ISAE-SUPAERO, études aérospatiales à la TUM et expérience en conception mécanique chez Lilium. Modélisation physique, Python scientifique et dispositifs d’essai aérospatiaux.",evidence:"Des preuves avant les affirmations.",all:"Tous",close:"Fermer",find:"Rechercher un projet, un sujet ou une page",none:"Aucun résultat. Essayez un autre terme.",journey:"Un parcours. Trois perspectives.",touch:"Parlons de vos projets.",print:"Imprimer le profil",capabilities:"Des compétences reliées aux projets."},
 de:{personal:"Persönlich",professional:"Beruflich",work:"Projekte",profile:"Profil",contact:"Kontakt",search:"Suchen",cv:"Lebenslauf herunterladen",intro:"Luft- und Raumfahrt. Anders betrachtet.",human:"Technik prägt mein Denken. Bewegung meinen Blick.",bio:"Aerodynamik und Antrieb. Ein Fundament im Maschinenbau. Ein Weg zwischen Indien, München und Toulouse — und eine Faszination für Bewegung.",selected:"Ausgewählte Projekte",research:"Von der Anforderung zum Modell.",explore:"Forschung entdecken",archive:"Vollständiges Profil entdecken",fallback:"Technische Unterlagen bleiben im englischen Original. Die Sprache der Oberfläche ist keine Aussage über Sprachkenntnisse.",overview:"Aerodynamik. Antrieb. Numerische Methoden.",proIntro:"Forschung an der ISAE-SUPAERO, Luft- und Raumfahrtstudien an der TUM und Konstruktionserfahrung bei Lilium. Physikalische Modellierung, wissenschaftliches Python und Prüfvorrichtungen.",evidence:"Nachweise vor Behauptungen.",all:"Alle",close:"Schließen",find:"Projekt, Thema oder Seite suchen",none:"Keine Treffer. Versuchen Sie einen anderen Begriff.",journey:"Ein Weg. Drei Perspektiven.",touch:"Sprechen wir über die Arbeit.",print:"Profil drucken",capabilities:"Kompetenzen mit Projektbezug."}
};
