"use client";
import {useState,useRef,useEffect} from "react";
import Link from "next/link";
import Image from "next/image";
import {NextIntlClientProvider,useTranslations} from "next-intl";
import {work,inventory,messages,type Locale,type Project} from "@/lib/flow-content";
import {FlowSculpture} from "./FlowSculpture";
import {ReaderLanguage} from "./ReaderLanguage";
import {ProjectScene} from "./ProjectScene";
import profile from "@/data/profile.json";
import "./flowstate.css";

export default function Flowstate({locale="en",view=[]}:{locale?:Locale;view?:string[]}) {
 return <NextIntlClientProvider locale={locale} messages={messages[locale]}><ReaderLanguage><Experience locale={locale} view={view}/></ReaderLanguage></NextIntlClientProvider>;
}
function Experience({locale,view}:{locale:Locale;view:string[]}) {
 const t=useTranslations(); const pro=view[0]==="pro"; const parts=pro?view.slice(1):view; const page=parts[0]||"home";
 const base=`/${locale}${pro?"/pro":""}`;
 const [query,setQuery]=useState(""); const [category,setCategory]=useState("All");
 const dialog=useRef<HTMLDialogElement>(null); const trigger=useRef<HTMLButtonElement>(null);
 const project=work.find(p=>p.id===parts[1]);
 const href=(path="")=>base+path;
 useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dataset.mode=pro?"professional":"personal";
 function key(e:KeyboardEvent){if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();dialog.current?.showModal();}}
 window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[locale,pro]);
 const nav=[{label:t("work"),url:href("/projects")},{label:t("profile"),url:href("/profile")},{label:t("contact"),url:href("/contact")}];
 const hits=work.filter(p=>(p.title+" "+p.tags.join(" ")+p.tools.join(" ")).toLowerCase().includes(query.toLowerCase()));
 const selected=["trace-fangeo","high-lift-aerodynamics","vorom-x-aerodynamics","dep-aircraft-aero","lilium-sandwich-structures"].map(id=>work.find(p=>p.id===id)).filter((p):p is Project=>!!p);
 function cards(items:Project[]){return <div className="fs-work-grid">{items.map((p,i)=><article key={p.id} className="fs-work-card"><div className="fs-scene"><ProjectScene id={p.id}/></div><div className="fs-card-copy"><span className="fs-kicker">{String(i+1).padStart(2,"0")} / {p.tags[0]}</span><h3><Link href={href(`/projects/${p.id}`)}>{p.title} ↗</Link></h3><p lang="en">{p.impact}</p></div></article>)}</div>}
 return <div className={`flowstate ${pro?"fs-pro":"fs-personal"}`}>
 <a className="fs-skip" href="#flow-content">Skip to content</a>
 <header className="fs-nav"><Link className="fs-brand" href={base}>rk<span> / FLOWSTATE</span></Link><nav aria-label="Main">{nav.map(n=><Link key={n.url} href={n.url}>{n.label}</Link>)}</nav><div className="fs-nav-tools"><div className="fs-modes"><Link aria-current={!pro?"page":undefined} href={`/${locale}`}>{t("personal")}</Link><Link aria-current={pro?"page":undefined} href={`/${locale}/pro`}>{t("professional")}</Link></div><select aria-label="Language" value={locale} onChange={e=>{window.location.href=`/${e.target.value}${view.length?"/"+view.join("/"):""}`;}}><option value="en">EN</option><option value="fr">FR</option><option value="de">DE</option></select><button ref={trigger} onClick={()=>dialog.current?.showModal()} aria-label={t("search")}>⌕</button></div></header>
 <main id="flow-content" key={base+parts.join("/")}>
 {page==="home" && <>{pro?<section className="fs-pro-hero fs-section"><div><span className="fs-kicker">REGHURAM KESAVAN / ENGINEERING</span><h1>{t("overview")}</h1><p>{t("proIntro")}</p><div className="fs-actions"><a className="fs-button" href="/resume.pdf">{t("cv")} ↓</a><Link href={href("/contact")}>{t("contact")} ↗</Link></div></div><Image src="/profile-hero.png" width={430} height={520} alt="Reghuram Kesavan" priority/><div className="fs-facts"><span>ISAE-SUPAERO <strong>TRACE FanGEO · DAEP</strong></span><span>LILIUM <strong>Mechanical design & testing</strong></span><span>MASTER’S CANDIDATE <strong>Expected December 2026</strong></span></div></section>:<><FlowSculpture/><section className="fs-person fs-section" id="the-person"><div><span className="fs-kicker">01 / THE PERSON BEHIND THE WORK</span><h2>{t("human")}</h2><p>{t("bio")}</p><Link className="fs-text-link" href={href("/profile")}>{t("archive")} ↗</Link></div><figure><Image src="/profile-hero.png" alt="Reghuram Kesavan" width={660} height={760}/><figcaption>REGHURAM KESAVAN · TOULOUSE, FRANCE</figcaption></figure></section></>}
 <section className="fs-flagship fs-section"><div><span className="fs-kicker">{pro?"01":"02"} / CURRENT RESEARCH · ISAE-SUPAERO</span><h2>{t("research")}</h2><p>TRACE FanGEO</p><p className="fs-muted" lang="en">Requirement-driven fan geometry and body-force-model preprocessing. Explore how design intent becomes an inspectable engineering model.</p><Link className="fs-text-link" href={href("/projects/trace-fangeo")}>{t("explore")} ↗</Link></div><TraceExplorer/></section>
 <section className="fs-section"><div className="fs-section-head"><div><span className="fs-kicker">{pro?"02":"03"} / ENGINEERING</span><h2>{t("selected")}</h2></div><Link href={href("/projects")}>{t("all")} ↗</Link></div>{pro?<div className="fs-evidence-list">{selected.map(p=><article key={p.id}><h3><Link href={href(`/projects/${p.id}`)}>{p.title} ↗</Link></h3><p>{p.impact}</p><details><summary>Verification & limitations</summary><p>{p.validation}</p></details></article>)}</div>:cards(selected.slice(1,5))}</section>
 <Capabilities base={base}/>
 {!pro&&<MotionStudy/>}
 <section className="fs-section fs-journey"><span className="fs-kicker">EDUCATION / EXPERIENCE</span><h2>{t("journey")}</h2><div className="fs-route">{[["01","India","Mechanical engineering","KTU · B.Tech (Honours) · 9.3/10"],["02","Munich","Aerospace & industry","TUM · Lilium · WARR Rocketry"],["03","Toulouse","Aerodynamics & propulsion","ISAE-SUPAERO · TRACE FanGEO"]].map(row=><div key={row[0]}><span>{row[0]}</span><h3>{row[1]}</h3><p>{row[2]}</p><small>{row[3]}</small></div>)}</div><Link href={href("/profile")}>{t("archive")} ↗</Link></section>
 {pro&&<section className="fs-section"><h2>Industry experience</h2>{profile.experience.slice(0,2).map(e=><article className="fs-record" key={e.company}><h3>{e.company}</h3><p>{e.role} · {e.period}</p><p>{e.description}</p></article>)}</section>}
 </>}
 {page==="projects"&&!project&&<section className="fs-section fs-page"><span className="fs-kicker">RESEARCH / DESIGN / METHODS</span><h1>{t("work")}</h1><p className="fs-notice">{t("fallback")}</p>{cards(work)}</section>}
 {page==="projects"&&project&&<section className="fs-section fs-page"><Link href={href("/projects")}>← {t("work")}</Link><div className="fs-case-heading"><span className="fs-kicker">{project.role}</span><h1>{project.title}</h1><p>{project.impact}</p></div><p className="fs-notice">{t("fallback")}</p>{project.id==="trace-fangeo"?<TraceExplorer/>:<div className="fs-case-scene"><ProjectScene id={project.id}/></div>}<div className="fs-case-body"><aside><span className="fs-kicker">METHODS & TOOLS</span>{project.tools.map(tool=><span key={tool}>{tool}</span>)}</aside><div>{[["Context",project.summary],["Problem",project.problem],["Method & contribution",project.approach],["Model / design",project.methods],["Verification & limitations",project.validation],["Result",project.results],["Learnings",project.learnings],["Next",project.next_steps]].map(([title,text])=><section key={title}><h2>{title}</h2><p lang="en">{text}</p></section>)}</div></div></section>}
 {page==="profile"&&<section className="fs-section fs-page"><span className="fs-kicker">REGHURAM KESAVAN</span><h1>{t("profile")}</h1><p>{t("proIntro")}</p><div className="fs-actions"><a href="/resume.pdf" className="fs-button">{t("cv")} ↓</a><button onClick={()=>window.print()}>{t("print")}</button></div><h2>Education</h2>{profile.education.map(e=><article className="fs-record" key={e.institution}><h3>{e.institution}</h3><p>{e.degree} · {e.period}</p><p>{e.details}</p></article>)}<h2>Languages</h2><div className="fs-language-list">{profile.languages.map(l=><span key={l.language}><strong>{l.language}</strong> {l.level}</span>)}</div><h2>Full public inventory</h2><p className="fs-notice">{t("fallback")}</p><div className="fs-filters"><input aria-label={t("find")} placeholder={t("find")} value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Category" value={category} onChange={e=>setCategory(e.target.value)}><option value="All">{t("all")}</option>{[...new Set(inventory.map(i=>i.category))].map(c=><option key={c}>{c}</option>)}</select></div><div className="fs-inventory">{inventory.filter(i=>(category==="All"||i.category===category)&&JSON.stringify(i).toLowerCase().includes(query.toLowerCase())&&(!pro||!/dance|cultural/i.test(i.category+" "+i.title))).map(i=><details key={i.id}><summary><span>{i.title}</span><small>{i.institution} · {i.period}</small></summary><p>{i.summary}</p></details>)}</div></section>}
 {page==="contact"&&<section className="fs-section fs-page fs-contact-page"><span className="fs-kicker">TOULOUSE / OPEN TO CONVERSATION</span><h1>{t("touch")}</h1><a className="fs-email" href={`mailto:${profile.email}`}>{profile.email} ↗</a><div className="fs-actions"><a href={profile.linkedin}>LinkedIn ↗</a><a href={profile.github}>GitHub ↗</a><a href="/resume.pdf">{t("cv")} ↓</a></div></section>}
 </main><footer className="fs-footer"><Link href={href("/contact")}><h2>{t("touch")} ↗</h2></Link><div><span>REGHURAM KESAVAN © {new Date().getFullYear()}</span><span>AERODYNAMICS / PROPULSION / CURIOSITY</span></div></footer>
 <dialog ref={dialog} className="fs-command" onClose={()=>{trigger.current?.focus();setQuery("");}}><div><h2>{t("search")}</h2><button onClick={()=>dialog.current?.close()}>{t("close")} ×</button></div><input autoFocus aria-label={t("find")} placeholder={t("find")} value={query} onChange={e=>setQuery(e.target.value)}/><nav>{nav.filter(n=>n.label.toLowerCase().includes(query.toLowerCase())).map(n=><Link onClick={()=>dialog.current?.close()} key={n.url} href={n.url}>{n.label} ↗</Link>)}{hits.map(p=><Link onClick={()=>dialog.current?.close()} key={p.id} href={href(`/projects/${p.id}`)}>{p.title} ↗</Link>)}{!hits.length&&<p>{t("none")}</p>}</nav></dialog>
 </div>
}
function TraceExplorer(){const [span,setSpan]=useState(50);const [layer,setLayer]=useState("Geometry"); const [stage,setStage]=useState(0);const stages=[{name:"Requirements",text:"Design requirements define the intended operating point. They are inputs, not proof of a realised fan performance."},{name:"Throughflow",text:"Analytical throughflow and radial equilibrium connect velocity triangles across the span. Assumptions and omitted physics remain explicit."},{name:"Geometry",text:"Blade parameterisation turns the radial description into inspectable geometry. This illustration is generic, not exported thesis geometry."},{name:"BFM fields",text:"Geometry-derived fields support body-force-model preprocessing. Generating these fields is not equivalent to validating a CFD solution."},{name:"Verification",text:"Analytical checks, coordinate consistency and reconstruction diagnostics precede physical validation. Full 3D RANS or rig validation is not claimed."}];return <div className="fs-trace"><div className="fs-tabs">{["Aero","Geometry","BFM"].map(l=><button key={l} aria-pressed={layer===l} onClick={()=>setLayer(l)}>{l}</button>)}</div><svg viewBox="0 0 640 420" role="img" aria-label={`Illustrative fan ${layer} view, selected span ${span} percent`}><defs><linearGradient id="blade"><stop stopColor="#4b806d"/><stop offset="1" stopColor="#d7ffed"/></linearGradient></defs><g transform="translate(320 210)">{Array.from({length:18},(_,i)=><path key={i} transform={`rotate(${i*20})`} d="M 30 -20 C 65 -90 116 -137 158 -144 L 181 -95 C 104 -85 72 -40 44 8 Z" fill={layer==="Geometry"?"url(#blade)":"none"} stroke="#bde8d4" strokeWidth={layer==="BFM"?2:0.8} opacity={.5+i/40}/>)}<circle r="32" fill="#122b24" stroke="#bde8d4"/><circle r={45+span*1.35} fill="none" stroke="#ffcb91" strokeDasharray="4 6"/>{layer==="Aero"&&Array.from({length:7},(_,i)=><path key={i} d={`M -260 ${i*40-120} Q 0 ${i*22-70} 260 ${i*40-120}`} stroke="#f1e2c7" fill="none" opacity=".65"/>)}{layer==="BFM"&&Array.from({length:12},(_,i)=><text key={i} transform={`rotate(${i*30}) translate(0 -205)`} fill="#ffcb91" fontSize="22">↑</text>)}</g></svg><label className="fs-slider">Radial inspection <output>{span}% span</output><input aria-label="Illustrative radial inspection" type="range" min="0" max="100" value={span} onChange={e=>setSpan(+e.target.value)}/></label><p className="fs-notice">Illustrative geometry · no simulated flow or performance data</p><div className="fs-stages">{stages.map((s,i)=><button key={s.name} aria-pressed={stage===i} onClick={()=>setStage(i)}>{String(i+1).padStart(2,"0")}<span>{s.name}</span></button>)}</div><p className="fs-stage-copy" role="status">{stages[stage].text}</p></div>}
function Capabilities({base}:{base:string}){const t=useTranslations();const [active,setActive]=useState("Python");const skills=["Python","ANSYS Fluent","XFOIL","Siemens NX","VLM","SU2"];const linked=work.filter(p=>p.tools.some(tool=>tool.toLowerCase().includes(active.toLowerCase())));return <section className="fs-section fs-capabilities"><span className="fs-kicker">METHOD → APPLICATION</span><h2>{t("capabilities")}</h2><div className="fs-cap-grid"><div className="fs-skills">{skills.map(s=><button aria-pressed={active===s} key={s} onClick={()=>setActive(s)}>{s}<span>↗</span></button>)}</div><div className="fs-skill-work" aria-live="polite"><span className="fs-kicker">{active} / PROJECT CONNECTIONS</span>{linked.map(p=><Link key={p.id} href={`${base}/projects/${p.id}`}>{p.title} ↗</Link>)}</div></div></section>}
function MotionStudy(){const [track,setTrack]=useState("Racing line");const [value,setValue]=useState(50);const paths:Record<string,string>={"Racing line":"M 50 230 C 120 30 220 50 245 150 S 410 380 540 130 S 720 180 730 240", "Rhythm":"M 30 200 C 100 20 150 380 220 200 S 350 20 420 200 S 560 380 650 200 S 740 50 770 180", "Precision":"M 60 250 L 270 250 Q 320 250 320 200 L 320 120 Q 320 80 380 80 L 680 80", "Play":"M 60 250 Q 310 -80 720 260"};return <section className="fs-section fs-motion"><div><span className="fs-kicker">04 / A DIFFERENT KIND OF FLOW</span><h2>Find the line.<br/>Feel the rhythm.</h2><p>F1, dance, Valorant and football. Different settings, the same attention to timing, movement and precision.</p><div className="fs-tabs">{Object.keys(paths).map(p=><button key={p} aria-pressed={track===p} onClick={()=>setTrack(p)}>{p}</button>)}</div></div><div><svg viewBox="0 0 800 400" role="img" aria-label={`${track}: decorative motion study`}><path d={paths[track]} fill="none" stroke="#243a35" strokeWidth="28"/><path d={paths[track]} fill="none" stroke="#bde8d4" strokeWidth="2" pathLength="100" strokeDasharray={`${value} 100`}/><path d={paths[track]} fill="none" stroke="#ffcb91" strokeWidth="8" strokeLinecap="round" pathLength="100" strokeDasharray=".1 100" strokeDashoffset={-value}/></svg><label className="fs-slider">Explore the trajectory <output>{value}%</output><input aria-label="Trajectory position" type="range" value={value} onChange={e=>setValue(+e.target.value)}/></label><p className="fs-notice">A visual study of movement, not a vehicle or ball simulation.</p></div></section>}
